// TEMPORARY DATA

export let role = "admin";

export const lecturersData = [
  {
    id: 1,
    lecturerId: "1234563890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      " https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Discrete Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    lecturerId: "1234563890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Analytics ", "Research Project"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    lecturerId: "1234563890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Programming"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    lecturerId: "1234563890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Database Management"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    lecturerId: "1234563890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Music", "Database Management"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    lecturerId: "1234563890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/312513/pexels-photo-312513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Analytics "],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    lecturerId: "1234563890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["IT Security", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    lecturerId: "1234563890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Discrete Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    lecturerId: "1234563890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Literature", "IT Security"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    lecturerId: "1234563890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043434/pexels-photo-1043434.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234563890",
    subjects: ["Programming"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "2025012345",
    name: "Liam Hart",
    email: "liam.hart@example.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=600",
    phone: "9876543210",
    course: 6,
    class: "2C",
    address: "45 Elm Street, Brookfield, NY",
  },
  {
    id: 2,
    studentId: "2025012346",
    name: "Emma Blake",
    email: "emma.blake@example.com",
    photo:
      "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543211",
    course: 6,
    class: "2C",
    address: "78 Pine Avenue, Brookfield, NY",
  },
  {
    id: 3,
    studentId: "2025012347",
    name: "Noah Brooks",
    email: "noah.brooks@example.com",
    photo:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543212",
    course: 6,
    class: "2C",
    address: "101 Cedar Lane, Brookfield, NY",
  },
  {
    id: 4,
    studentId: "2025012348",
    name: "Ava Morris",
    email: "ava.morris@example.com",
    photo:
      "https://images.pexels.com/photos/1130628/pexels-photo-1130628.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543213",
    course: 6,
    class: "2C",
    address: "22 Willow Way, Brookfield, NY",
  },
  {
    id: 5,
    studentId: "2025012349",
    name: "Ethan Reyes",
    email: "ethan.reyes@example.com",
    photo:
      "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543214",
    course: 6,
    class: "2C",
    address: "56 Maple Drive, Brookfield, NY",
  },
  {
    id: 6,
    studentId: "2025012350",
    name: "Olivia Lane",
    email: "olivia.lane@example.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543215",
    course: 6,
    class: "2C",
    address: "90 Birch Road, Brookfield, NY",
  },
  {
    id: 7,
    studentId: "2025012351",
    name: "Mason Lee",
    email: "mason.lee@example.com",
    photo:
      "https://images.pexels.com/photos/1680172/pexels-photo-1680172.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543216",
    course: 6,
    class: "2C",
    address: "12 Oak Hill, Brookfield, NY",
  },
  {
    id: 8,
    studentId: "2025012352",
    name: "Sophia Grant",
    email: "sophia.grant@example.com",
    photo:
      "https://images.pexels.com/photos/1987301/pexels-photo-1987301.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543217",
    course: 6,
    class: "2C",
    address: "77 Aspen Court, Brookfield, NY",
  },
  {
    id: 9,
    studentId: "2025012353",
    name: "Lucas Hale",
    email: "lucas.hale@example.com",
    photo:
      "https://images.pexels.com/photos/3770581/pexels-photo-3770581.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543218",
    course: 6,
    class: "2C",
    address: "14 Redwood Blvd, Brookfield, NY",
  },
  {
    id: 10,
    studentId: "2025012354",
    name: "Isabella Rhodes",
    email: "isabella.rhodes@example.com",
    photo:
      "https://images.pexels.com/photos/1809644/pexels-photo-1809644.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "9876543219",
    course: 6,
    class: "2C",
    address: "88 Cypress Crescent, Brookfield, NY",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234563890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Discrete Math",
    lecturers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "IT Security",
    lecturers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Analytics ",
    lecturers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Research Project",
    lecturers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Programming",
    lecturers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "Database Management",
    lecturers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 3,
    name: "Geography",
    lecturers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    lecturers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    lecturers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    lecturers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    class: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    class: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    class: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    class: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    class: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    class: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 3,
    name: "3A",
    capacity: 18,
    class: 3,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    class: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    class: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    class: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Discrete Math",
    class: "1A",
    lecturer: "Tommy Wise",
  },
  {
    id: 2,
    subject: "IT Security",
    class: "2A",
    lecturer: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    lecturer: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    lecturer: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    lecturer: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    lecturer: "Bettie Oliver",
  },
  {
    id: 3,
    subject: "Database Management",
    class: "6A",
    lecturer: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    lecturer: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Analytics ",
    class: "6C",
    lecturer: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Research Project",
    class: "4B",
    lecturer: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Discrete Math",
    class: "1A",
    lecturer: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "IT Security",
    class: "2A",
    lecturer: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    lecturer: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    lecturer: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    lecturer: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    lecturer: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Database Management",
    class: "6A",
    lecturer: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    lecturer: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Analytics ",
    class: "3A",
    lecturer: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Research Project",
    class: "8A",
    lecturer: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Discrete Math",
    class: "1A",
    lecturer: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "IT Security",
    class: "2A",
    lecturer: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    lecturer: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    lecturer: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    lecturer: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    lecturer: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Database Management",
    class: "6A",
    lecturer: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    lecturer: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Analytics ",
    class: "3A",
    lecturer: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Research Project",
    class: "8A",
    lecturer: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Discrete Math",
    class: "1A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "IT Security",
    class: "2A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Database Management",
    class: "6A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Analytics ",
    class: "3A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Research Project",
    class: "8A",
    lecturer: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    class: "1A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    class: "2A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    class: "3A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    class: "4A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Music Concert",
    class: "5A",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    class: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Lake Trip",
    class: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    class: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Art Exhibition",
    class: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    class: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Discrete Math Test",
    class: "4A",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 3A Discrete Math Test",
    class: "3A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Discrete Math Test",
    class: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 6A Discrete Math Test",
    class: "6A",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Discrete Math Test",
    class: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 2A Discrete Math Test",
    class: "2A",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 4C Discrete Math Test",
    class: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Discrete Math Test",
    class: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Discrete Math Test",
    class: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Discrete Math Test",
    class: "1C",
    date: "2025-01-01",
  },
];

// Events scheduled across their date, **January is considered as "0" in js
export const calendarEvents = [
  {
    title: "Discrete Math",
    allDay: false,
    start: new Date(2025, 3, 12, 8, 0),
    end: new Date(2025, 3, 12, 8, 45),
  },
  {
    title: "IT Security",
    allDay: false,
    start: new Date(2025, 3, 12, 9, 0),
    end: new Date(2025, 3, 12, 9, 45),
  },
  {
    title: "Programming",
    allDay: false,
    start: new Date(2025, 3, 12, 10, 0),
    end: new Date(2025, 3, 12, 10, 45),
  },
  {
    title: "Analytics ",
    allDay: false,
    start: new Date(2025, 3, 12, 11, 0),
    end: new Date(2025, 3, 12, 11, 45),
  },
  {
    title: "Research Project",
    allDay: false,
    start: new Date(2025, 3, 13, 13, 0),
    end: new Date(2025, 3, 13, 13, 45),
  },
  {
    title: "Database Management",
    allDay: false,
    start: new Date(2025, 3, 12, 14, 0),
    end: new Date(2025, 3, 12, 14, 45),
  },
  {
    title: "IT Security",
    allDay: false,
    start: new Date(2025, 3, 13, 9, 0),
    end: new Date(2025, 3, 13, 9, 45),
  },
  {
    title: "Programming",
    allDay: false,
    start: new Date(2025, 3, 13, 10, 0),
    end: new Date(2025, 3, 13, 10, 45),
  },
  {
    title: "Analytics ",
    allDay: false,
    start: new Date(2025, 3, 13, 11, 0),
    end: new Date(2025, 3, 13, 11, 45),
  },

  {
    title: "Database Management",
    allDay: false,
    start: new Date(2025, 3, 13, 14, 0),
    end: new Date(2025, 3, 13, 14, 45),
  },
  {
    title: "Discrete Math",
    allDay: false,
    start: new Date(2025, 3, 14, 8, 0),
    end: new Date(2025, 3, 14, 8, 45),
  },
  {
    title: "Programming",
    allDay: false,
    start: new Date(2025, 3, 14, 10, 0),
    end: new Date(2025, 3, 14, 10, 45),
  },

  {
    title: "Research Project",
    allDay: false,
    start: new Date(2025, 3, 14, 13, 0),
    end: new Date(2025, 3, 14, 13, 45),
  },
  {
    title: "Database Management",
    allDay: false,
    start: new Date(2025, 3, 14, 14, 0),
    end: new Date(2025, 3, 13, 14, 45),
  },
  {
    title: "IT Security",
    allDay: false,
    start: new Date(2025, 3, 15, 9, 0),
    end: new Date(2025, 3, 15, 9, 45),
  },
  {
    title: "Programming",
    allDay: false,
    start: new Date(2025, 3, 15, 10, 0),
    end: new Date(2025, 3, 15, 10, 45),
  },
  {
    title: "Analytics ",
    allDay: false,
    start: new Date(2025, 3, 15, 11, 0),
    end: new Date(2025, 3, 15, 11, 45),
  },

  {
    title: "Database Management",
    allDay: false,
    start: new Date(2025, 3, 15, 14, 0),
    end: new Date(2025, 3, 15, 14, 45),
  },
  {
    title: "Discrete Math",
    allDay: false,
    start: new Date(2025, 3, 16, 8, 0),
    end: new Date(2025, 3, 16, 8, 45),
  },
  {
    title: "IT Security",
    allDay: false,
    start: new Date(2025, 3, 16, 9, 0),
    end: new Date(2025, 3, 16, 9, 45),
  },

  {
    title: "Analytics ",
    allDay: false,
    start: new Date(2025, 3, 16, 11, 0),
    end: new Date(2025, 3, 16, 11, 45),
  },
  {
    title: "Research Project",
    allDay: false,
    start: new Date(2025, 3, 17, 13, 0),
    end: new Date(2025, 3, 17, 13, 45),
  },
  {
    title: "Database Management",
    allDay: false,
    start: new Date(2025, 3, 17, 14, 0),
    end: new Date(2025, 3, 17, 14, 45),
  },
];
